package main.java.meleeauthority;

public class MeleeCharacter {

    public String id;
    public String name;
    public Float InitWalkVel;
    public Float WalkAccel;
    public Float WalkMaxVel;
    public Float SlowWalkMax;
    public Float MidWalkPoint;
    public Float FastWalkMin;
    public Float Friction;
    public Float DashInitVel;
    public Float DashAccelA;
    public Float DashAccelB;
    public Float DashTermVel;
    public Float RunAnimScal;
    public Float RunAccel;
    public Float JumpFrames;
    public Float JumpHInitVel;
    public Float JumpVInitVel;
    public Float JumpMomentMult;
    public Float JumpHMaxVel;
    public Float SHVInitVel;
    public Float AirJMult;
    public Float DblJMult;
    public Integer NumJumps;
    public Float Gravity;
    public Float TermVel;
    public Float AirMobA;
    public Float AirMobB;
    public Float MaxAirHVel;
    public Float AirFriction;
    public Float FFTermVel;
    public Float Unknown31;
    public Integer Jab2Window;
    public Integer Jab3Window;
    public Integer ChDirFrames;
    public Integer Weight;
    public Float ModelScaling;
    public Float ShieldSize;
    public Float ShldBrkInitVel;
    public Integer RpdJabWindow;
    public Float LdgJmpHVel;
    public Float LdgJmpVVel;
    public Float ThrowVel;
    public Integer StarDmg;
    public Float ALag;
    public Float NLag;
    public Float FLag;
    public Float BLag;
    public Float ULag;
    public Float DLag;
    public Float VMdlScaling;
    public Float WJmpHVel;
    public Float WJmpVVel;
}
